[package]
name = "aes-gcm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
aes-gcm = {version="0.9.4", feature="aes"}
aead = "0.4.3"
